ASP.NET & Bootstrap/04_EF_ORM_DB_Programing/04_EF_ORM_DB_Programing/Models/Memos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_EF_ORM_DB_Programing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memos
    {
        public int MemoIDX { get; set; }
        public string Name { get; set; }
        public string MemoContent { get; set; }
    }
}

ASP.NET & Bootstrap/04_EF_ORM_DB_Programing/04_EF_ORM_DB_Programing/Controllers/MemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using _04_EF_ORM_DB_Programing.Models;
using System.Diagnostics;

namespace _04_EF_ORM_DB_Programing.Controllers
{
    public class MemoController : Controller
    {
        ExamHomePageEntities db = new ExamHomePageEntities();   //DB 처리 객체

        /* Action
        Action 메서드는 외부 요청에 반응하여 결과를 리턴하는 메서드이다.
        웹의 Request를 받아들여 처리 후 출력물인 ActionResult 객체를 반환한다.
        ActinResult는 추상클래스로서 리턴 결과물에 따라서 파생된 클래스들을 가진다.

        ActionResult의 파생 클래스
        - ViewResult, PartialViewResult : HTML 반환, return View(), PartialView()
        - EmptyResult : 빈 결과
        - ContentResult : 문자열을 반환, return Content()
        - FileContentResult, FilePathResult, FileStreamResult : 파일을 반환, return File()
        - JavaScriptResult : JS를 반환, return JavaScript()
        - JsonResult : Json을 반환 : return Json()
        - RedirectResult, RedirectToRouteResult : 새 URL 혹은 Action으로 redirect, return Redirect(), RedirectToRoute(), RedirectToAction()
        - HttpUnauthorizedResult : HTTP 403 반환

        */
        // GET: Memo
        [HttpGet]
        public ActionResult List()
        {
            ViewBag.Message = "message test";
            ViewData["mykey"] = "myvalue";
            List<Memos> list = db.Memos.ToList();   //C#에서의 모델 클래스 사용
            return View(list);  //Controller 베이스 클래스의 View() 메서드 호출. 메서드와 동일한 경로의 html 파일을 렌더링한 결과인 ViewResult 객체를 리턴한다.
        }

        /* Controller에서 View로 데이터 전달 방식
        1. View() 메서드의 파라미터로 Model 객체 전달
        2. ViewBag(dynamic) : 개발자의 임의의 속성을 지정하여 저장할 수 있다. 내부적으로 ViewData 객체를 사용하며 해시테이블 데이터를 dynamic 타입으로 편리하게 제공하기 위한 Wrapper
        3. ViewData(컬렉션) : Dictionary(해시테이블) 타입으로 key에 value를 지정하여 넘길 수 있다.
        */

        [HttpGet]
        public ActionResult Entry()
        {
            Memos memo = new Memos();
            return View(memo);
        }

        [HttpPost]
        public ActionResult Entry(Memos memo)
        {
            Debug.WriteLine("hello");
            Console.WriteLine("test");
            try
            {
                db.Memos.Add(memo);
                db.SaveChanges(); // commit
                ViewBag.Result = "OK";
            }
            catch (Exception ex)
            {
                Trace.WriteLine(ex);
                ViewBag.Result = "FAIL";
            }

            return View(memo);
        }
        [HttpGet]
        public ActionResult Edit(string idx)
        {
            Memos memo = db.Memos.Where(m => m.MemoIDX == int.Parse(idx)).FirstOrDefault();
            return View(memo);
        }

    }
}

ASP.NET & Bootstrap/04_EF_ORM_DB_Programing/04_EF_ORM_DB_Programing/Views/Memo/Edit.cshtml
@using _04_EF_ORM_DB_Programing.Models;
@model Memos
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<p>입력</p>
<form method="post" action="@Url.Action("Entry", "Memo")">
    @Html.HiddenFor(m => m.Name, new { value = Model.MemoIDX })
    이름 입력 : @Html.TextBoxFor(m => m.Name, new { value = Model.Name })
    내용 입력 : @Html.TextBoxFor(m => m.MemoContent, new { value = Model.MemoContent })
    <button type="submit">전송</button>
</form>


@section scripts {
    <script>
        var result = '@ViewBag.Result';
        if (result == 'OK') {
            alert("정상적으로 등록되었습니다.");
            location.href = "/memo/list";
        }
        else if (result == 'FAIL') {
            alert("등록을 실패하였습니다.");
            location.href = "/memo/list";
        }
    </script>
}

ASP.NET & Bootstrap/04_EF_ORM_DB_Programing/04_EF_ORM_DB_Programing/Views/Memo/Entry.cshtml
@using _04_EF_ORM_DB_Programing.Models;
@model Memos
@{
    ViewBag.Title = "Entry";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<p>입력</p>
<form method="post" action="@Url.Action("Entry", "Memo")">
    이름 입력 : @Html.TextBoxFor(m => m.Name, new { placeholder = "이름을 입력하세요" })
    내용 입력 : @Html.TextBoxFor(m => m.MemoContent, new { placeholder = "내용을 입력하세요" })
    <button type="submit">전송</button>
</form>


@section scripts {
    <script>
        var result = '@ViewBag.Result';
        if (result == 'OK') {
            alert("정상적으로 등록되었습니다.");
            location.href = "/memo/list";
        }
        else if (result == 'FAIL') {
            alert("등록을 실패하였습니다.");
            location.href = "/memo/list";
        }
    </script>
}

ASP.NET & Bootstrap/04_EF_ORM_DB_Programing/04_EF_ORM_DB_Programing/Views/Memo/List.cshtml
@using _04_EF_ORM_DB_Programing.Models;
@model IEnumerable<Memos>


@{
    ViewBag.Title = "Entry";
    Layout = "~/Views/Shared/_PageLayout.cshtml";
}

<p>컨텐츠 페이지</p>

<table border="1">
    <tr>
        <th width="50">번호</th>
        <th width="150">이름</th>
        <th width="600">내용</th>
        <th width="100">비고</th>
    </tr>
    @{ 
        int idx = 1;
    }
    @foreach(var memo in Model)
    {
        <tr>
            <td>@idx</td>
            <td>@memo.Name</td>
            <td>@memo.MemoContent</td>
            <td>
                <button onclick="location.href='/Memo/Edit?idx=@memo.MemoIDX'" >수정</button>
                <button onclick="location.href='/Memo/Delete?idx=@memo.MemoIDX'" >삭제</button>
            </td>
        </tr>
        idx++;
    }
</table>
<a href="/Memo/Entry">Register</a>
<p>@ViewData["mykey"]</p>
<p>@ViewBag.Message</p>